{{- if .Values.scarletdme.user.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scarletdme.fullname" . }}-credentials
  labels:
    {{- include "scarletdme.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.scarletdme.user.password | b64enc | quote }}
{{- end }}

