apiVersion: v1
kind: Service
metadata:
  name: {{ include "scarletdme.fullname" . }}
  labels:
    {{- include "scarletdme.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.qmServerPort }}
      targetPort: qmserver
      protocol: TCP
      name: qmserver
    - port: {{ .Values.service.qmClientPort }}
      targetPort: qmclient
      protocol: TCP
      name: qmclient
  selector:
    {{- include "scarletdme.selectorLabels" . | nindent 4 }}


